HOSTS:
  el7:
    roles:
      - default
      - el7
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/7/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt
      simpdeps:
        baseurl: https://packagecloud.io/simp-project/6_X_Dependencies/el/$releasever/$basearch
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://yum.puppet.com/RPM-GPG-KEY-puppetlabs
          - https://yum.puppet.com/RPM-GPG-KEY-puppet
          - https://apt.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-96
          - https://artifacts.elastic.co/GPG-KEY-elasticsearch
          - https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
