#!/usr/bin/expect -f

set user [lindex $argv 0]
set key  [lindex $argv 1]
set pass [lindex $argv 2]
set host [lindex $argv 3]
set output [exec oathtool --totp $key]
set timeout 10

spawn ssh -o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=1 $host -l $user

expect {
    "*One-time password*" {
        send_user "One-time password"
        send "$output\r"
        expect "*assword:" {
            send_user "password (for $user)"
            send "$pass\r"
            exp_continue
        }
        exp_continue
    } -re "$user@.+\[\$#]*" {
        send_user "TOTP test: success\n"
        exit 0
    }
}
send_user "TOTP test: failure\n"
exit 1
