---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh
    concat:
      # master is at 4.0.1, but we are bound to < 4.0.0 in our metadata.json
      repo: https://github.com/simp/puppetlabs-concat
      ref: 3.0.0
    haveged:
      repo: https://github.com/simp/puppet-haveged
      branch: simp-master
    iptables: https://github.com/simp/pupmod-simp-iptables
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pki: https://github.com/simp/pupmod-simp-pki
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    simplib: https://github.com/simp/pupmod-simp-simplib
    sssd: https://github.com/simp/pupmod-simp-sssd
    stdlib: https://github.com/simp/puppetlabs-stdlib
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    ssh: "#{source_dir}"
