---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core:
      repo: https://github.com/simp/augeasproviders_core
      branch: simp-master
    augeasproviders_grub:
      repo: https://github.com/simp/augeasproviders_grub
      branch: simp-master
    augeasproviders_ssh:
      repo: https://github.com/simp/augeasproviders_ssh
      branch: simp-master
    haveged:
      repo: https://github.com/simp/puppet-haveged
      branch: simp-master
    iptables: https://github.com/simp/pupmod-simp-iptables
    pki: https://github.com/simp/pupmod-simp-pki
    simpcat: https://github.com/simp/pupmod-simp-simpcat
    simplib: https://github.com/simp/pupmod-simp-simplib
    sssd: https://github.com/simp/pupmod-simp-sssd
    stdlib:
      repo: https://github.com/simp/puppetlabs-stdlib
      branch: simp-master
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    ssh: "#{source_dir}"
