---
fixtures:
  repositories:
    auditd:
      repo: https://github.com/simp/pupmod-simp-auditd
      branch: 5.X
    augeasproviders_core:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_core
    augeasproviders_grub:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_grub
    augeasproviders_ssh:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_ssh
    compliance_markup:
      repo: https://github.com/simp/pupmod-simp-compliance_markup
      branch: 5.X
    haveged:
      branch: 5.X
      repo: https://github.com/simp/puppet-haveged
    iptables:
      repo: https://github.com/simp/pupmod-simp-iptables
      branch: 5.X
    pki:
      repo: https://github.com/simp/pupmod-simp-pki
      branch: 5.X
    simpcat:
      repo: https://github.com/simp/pupmod-simp-simpcat
      branch: 5.X
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      branch: 5.X
    sssd:
      repo: https://github.com/simp/pupmod-simp-sssd
      branch: 5.X
    stdlib:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-stdlib
    tcpwrappers:
      repo: https://github.com/simp/pupmod-simp-tcpwrappers
      branch: 5.X
  symlinks:
    ssh: "#{source_dir}"
