HOSTS:
  el7-server:
    roles:
      - default
      - server
      - el7
      - el7-server
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  el7-client:
    roles:
      - client
      - el7
      - el7-client
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  el6-server:
    roles:
      - server
      - el6
      - el6-server
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant
  el6-client:
    roles:
      - client
      - el6
      - el6-client
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant
CONFIG:
  log_level:       verbose
  type:            aio
  vagrant_memsize: 256
